### ISSUE TITLE
The string universal unique identifier (UUID) is invalid. (Exception from HRESULT: 0x800706A9

### ISSUE THREAD

**Issue by codaamok** [nyanhp/GetMissingUpdates#3]
Have you ever noticed ..
```powershell
$UpdateSearcher.ServiceID = $UpdateService.ServiceID
```
... throw the below exception before?

```code
The string universal unique identifier (UUID) is invalid. (Exception from HRESULT: 0x800706A9)
At C:\kworking\tools\Scan-UpdatesOffline.ps1:13 char:1
+ $UpdateSearcher.ServiceID = $UpdateService.ServiceID
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
```

There's several [me too's](https://gallery.technet.microsoft.com/scriptcenter/Using-WUA-to-Scan-for-f7e5e0be/view/Discussions) for some other similar script on TechNet so I'm definitely not the only one. Just curious if you've come across it?

Either putting the `$UpdateService.ServiceID` into a variable first and then feeding it to `$UpdateSearcher` works, or strong typing it like so also works:

```powershell
$UpdateSearcher.ServiceID = [string]($UpdateService.ServiceID)
```

`$UpdateService.ServiceID` is absolutely a string type. No idea why it can't just directly feed in to `$UpdateSearcher.ServiceID` property.

**Comment by nyanhp** [comment]
Great work on the PR, thank you very much. Good to see that this code is actually being used :)
